name: Release and Sign

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    - name: Configure Git
      run: |
        git config --global user.name "Pono Finlayson"
        git config --global user.email "ponofinlayson@hotmail.com"
    
    - name: Create distribution package
      run: |
        # Create dist directory
        mkdir -p dist
        
        # Copy core files only (exclude documentation to preserve signatures)
        cp index.html dist/
        cp styles.css dist/
        cp script.js dist/
        cp manifest.json dist/
        cp package.json dist/
        cp install.bat dist/
        cp install.sh dist/
        cp install.js dist/
        cp QUICKSTART.md dist/
        
        # Copy themes directory
        cp -r themes dist/
        
        # Create ZIP package
        cd dist
        zip -r ../grouped-links-v${{ github.ref_name }}.zip .
        cd ..
    
    - name: Create checksums
      run: |
        # Create checksums (always done)
        sha256sum grouped-links-v${{ github.ref_name }}.zip > grouped-links-v${{ github.ref_name }}.zip.sha256
        sha512sum grouped-links-v${{ github.ref_name }}.zip > grouped-links-v${{ github.ref_name }}.zip.sha512
    
    - name: Sign package with GPG (Optional)
      continue-on-error: true
      run: |
        # Only sign if GPG_PRIVATE_KEY secret exists
        if [ -n "${{ secrets.GPG_PRIVATE_KEY }}" ]; then
          # Import GPG key
          echo "${{ secrets.GPG_PRIVATE_KEY }}" | gpg --batch --import || echo "GPG import failed"
          
          # Sign the package
          gpg --batch --armor --detach-sign grouped-links-v${{ github.ref_name }}.zip || echo "GPG signing failed"
        fi
    
    - name: Prepare release files
      run: |
        # Create a file list for release
        echo "grouped-links-v${{ github.ref_name }}.zip" > release-files.txt
        echo "grouped-links-v${{ github.ref_name }}.zip.sha256" >> release-files.txt
        echo "grouped-links-v${{ github.ref_name }}.zip.sha512" >> release-files.txt
        
        # Add .asc file if it exists
        if [ -f "grouped-links-v${{ github.ref_name }}.zip.asc" ]; then
          echo "grouped-links-v${{ github.ref_name }}.zip.asc" >> release-files.txt
        fi
        
        # List files to be uploaded
        cat release-files.txt
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          grouped-links-v${{ github.ref_name }}.zip
          grouped-links-v${{ github.ref_name }}.zip.sha256
          grouped-links-v${{ github.ref_name }}.zip.sha512
          grouped-links-v${{ github.ref_name }}.zip.asc
        body: |
          # Grouped Links v${{ github.ref_name }}
          
          A beautiful, modern homepage for Chromium-based browsers featuring theme customization, Google search integration, and organized link groups.
          
          ## ✨ Features
          
          - **6 Built-in Themes**: Switch between Default, Ocean Blue, Sunset, Forest Green, Minimal Light, and Modern Dark themes
          - **Theme Switcher**: Easy theme selection with persistent preferences
          - **Google Search**: Built-in search bar that opens results in new tabs
          - **Smart Card Management**: 4x3 grid layout with alphabetical sorting
          - **Easy Link Addition**: Click the "+" button in card title bars to add links
          - **Form-Based Editing**: Clean modal forms for adding and editing links
          - **Group Management**: Move links between groups via dropdown in edit form
          - **Ctrl+Click Navigation**: Hold Ctrl and click links to open in background tabs (stays on homepage)
          - **Dynamic Favicons**: Automatic favicon detection based on URLs
          - **Mobile Responsive**: Works perfectly on all devices
          - **Local Storage**: All data saved locally in your browser
          
          ## 🎨 Themes
          
          - **Default** - Original dark blue gradient (recommended)
          - **Ocean Blue** - Bright blue tones
          - **Sunset** - Warm orange and pink tones
          - **Forest Green** - Natural green tones
          - **Minimal Light** - Clean light theme
          - **Modern Dark** - Modern dark theme
          
          ## 🔐 Verification
          
          ### Verify Checksum (Recommended)
          
          **Windows (PowerShell):**
          ```powershell
          Get-FileHash grouped-links-v${{ github.ref_name }}.zip -Algorithm SHA256
          # Compare with the value in the .sha256 file
          ```
          
          **Mac/Linux:**
          ```bash
          shasum -a 256 grouped-links-v${{ github.ref_name }}.zip
          # Compare with the value in the .sha256 file
          ```
          
                     ### Verify GPG Signature (Optional)
           
           If you want to verify the GPG signature:
           
           **Step 1:** Download the public key from the repository:
           ```bash
           # Option A: From GitHub (recommended)
           curl -o public-key.asc https://raw.githubusercontent.com/ponofinlayson-web/cursor/main/public-key-github.asc
           
           # Option B: Or clone and use the file from the repo
           git clone https://github.com/ponofinlayson-web/cursor.git
           cd cursor
           ```
           
           **Step 2:** Import the public key:
           ```bash
           gpg --import public-key.asc
           # Or if you cloned the repo:
           gpg --import public-key-github.asc
           ```
           
           **Step 3:** Verify the signature:
           ```bash
           gpg --verify grouped-links-v${{ github.ref_name }}.zip.asc
           ```
           
           You should see: **"Good signature from Pono Finlayson"** ✅
          
          ## 🚀 Installation
          
          1. Download the ZIP file
          2. Extract to any folder
          3. Double-click `index.html`
          4. Set as homepage in your browser settings
          
          See `QUICKSTART.md` for detailed installation and usage instructions.
          
          ## 📄 License
          
          MIT License - Free to use, modify, and distribute.
          
          ---
          
          **Author**: Pono Finlayson  
          **License**: MIT  
          **Version**: ${{ github.ref_name }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
